### ISSUE TITLE
Building Rust binaries in CMake project(?)

### ISSUE THREAD

**Issue by val-ms** [micahsnyder/cmake-rust-demo#5]
At present this demo only builds static libs from Rust crates for use in C/C++ projects.  It seems reasonable that someone would want to replace their C/C++ executables with Rust executables while still building a mixed C/C++ & Rust shared library.

Eg: for the clamav project, we may wish to replace SigTool or ClamSubmit, which are fairly trivial programs, with Rust executables that still depend on libclamav.  This does get a whole lot more complicated because then the Rust interface to the C shared lib must be present.  For ClamAV, would that mean integrating something like `clamav-sys` & `clamav-rs` into the main ClamAV repository?  Or is the best solution then to migrate SigTool and such out entirely into their own repositories (perhaps not ideal)?

This question requires some investigation.

**Comment by apthorpe** [comment]
I have a simpler use case where I have a pure Rust application that I want to package into platform-specific installers using CPack. With C/C++/Fortran/etc executables, you use `include(GNUInstallDirs)` to define standard-ish installation locations then use `install(TARGETS <X>)` where `<X>` is the executable target name. CMake then translates that `install()` directive into something CPack can build installers with. I've been using Corrosion (https://github.com/AndrewGaspar/corrosion) as the CMake-`cargo` interface (I found it before this project) and while I can convince it to run `cargo` and create executables, I don't have a CMake target name or a sane way of detecting the binary artifacts from `cargo build` to pass on to `install()` in CMake.

I'd ask that if you decide to support adding Rust binaries to a CMake project that you expose the build target or the locations of compiled binaries back to CMake.

Also, for examples of creating `setup.exe`, `.msi`, `.nupkg`, `.deb`, `.rpm`, and `.dmg` (Apple DragNDrop) installers along with `.zip` and `.tar` archives using CPack, see https://gitlab.com/apthorpe/Castlequest/-/blob/cmakify2/CMakeLists.txt That CMake configuration sets up a lot of package-related info before the build process (name, maintainer, description, license, *etc.*) and makes use of the `install()` directives for each of the binaries and libraries that get built. The detail for building each of the installers is located at the end of the script (line 737 onward); the recipe makes use of `FindNSIS.cmake` and `FindWIX.cmake` for supporting those Windows packagers and a few `find_program()` and `find_package()` calls to find utilities for creating `.deb`, `.rpm`, and `.nupkg` packages. I've tested this setup on Windows, MacOS, and Linux for several different projects and it seems to work without much trouble.

**Comment by val-ms** [comment]
Hi @apthorpe  I'm so sorry I only just saw this comment. It slipped by me in the noise. :( 

> I'd ask that if you decide to support adding Rust binaries to a CMake project that you expose the build target or the locations of compiled binaries back to CMake.

This would definitely be a goal.  The CMake target should have the file so you can install or package with CPack. 

I've been procrastinating adding this feature because my work-project that leverages the `FindRust.cmake` module from this project only has need of static libraries from Rust right now.  But I do expect we'll need to build executables with Rust (Cargo) in the future as well. 

I'm also using this FindRust.cmake method for the "rustify" effort on the bzip2 project https://gitlab.com/bzip2/bzip2/-/tree/feature/rustify
